{"name": "Получение заказа неавторизованного пользователя", "status": "passed", "start": 1706479168958, "stop": 1706479169197, "uuid": "af0eb3ec-99bb-4f07-aff4-7aee1ebd6631", "historyId": "57698cbd913e64a23edcc2d8f27d860e", "testCaseId": "57698cbd913e64a23edcc2d8f27d860e", "fullName": "tests.test_get_user_orders.TestGetOrders#test_get_order_unauthorized_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "DESKTOP-29U91I9"}, {"name": "thread", "value": "24328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}